name: Docker Image CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up appconfig.development.json
        run: |
          # Crear appconfig.json
          echo '{
          "https_port": 443,
          "env": "Development"
          }'  > Netcore.Web.Api/appsettings.json
          
          # Crear appsettings.json
          echo '{
            "https_port": 443,
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetcore": "Warning"
              }
            },
            "env": "Development",
            "AllowedHosts": "*",
            "ConnectionStrings": {
              "Netcore": "${{ secrets.NETCORE }}"
            },
            "Secret": "${{ secrets.SECRETKEY }}"
          }' > Netcore.Web.Api/appsettings.Development.json
          
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin

      - name: Build the Docker image
        id: build-image
        run: |
          docker build . --file Dockerfile --tag netcoreback:latest

      - name: Tag the Docker image
        run: |
          docker tag netcoreback:latest r998/netcoreback:latest

      - name: Push the Docker image to Docker Hub
        run: |
          docker push r998/netcoreback:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEANHOST }}
          username: ${{ secrets.DIGITALOCEANUSERNAME }}
          password: ${{ secrets.DIGITALOCEANPASSWORD }}
          port: 22
          script: |
            docker stop activofijo || true
            docker rm activofijo || true
            docker pull r998/netcoreback:latest
            docker run --name activofijo -d -p 443:80  r998/netcoreback:latest
