name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      # Crea el archivo appsettings.json
    - name: Set up appconfig.development.json
      run: |
          # Crear appconfig.json
          echo '{
          "env": "Development"
          //"env": "Local",
          //"env": "Production",
          //"env": "Qa"
          }'  > appconfig.json
          echo '{
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetcore": "Warning"
              }
            },
            "env": "Development",
            "AllowedHosts": "*",
            "ConnectionStrings": {
              "Netcore": "'"$NETCORE"'"
            },
            "Secret": "'"$SECRETKEY"'",
          }' > appsettings.temp.json
          mv appsettings.temp.json appsettings.Development.json
