name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      # Crea el archivo appsettings.json
    - name: Set up appconfig.development.json
      run: |
          # Crear appconfig.json
          echo '{
          "env": "Development"
          }'  > appconfig.json
          echo '{
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetcore": "Warning"
              }
            },
            "env": "Development",
            "AllowedHosts": "*",
            "ConnectionStrings": {
              "Netcore": "'"$NETCORE"'"
            },
            "Secret": "'"$SECRETKEY"'",
          }' > appsettings.temp.json
          mv appsettings.temp.json appsettings.Development.json
    - name: Build the Docker image
      id: build-image
      run: |
         docker build . --file Dockerfile --tag my-image-name:latest
         echo "::set-output name=image-tag::latest"

    - name: Export image tag
      run: echo "The image tag is ${{ steps.build-image.outputs.image-tag }}"

      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEANHOST }}
          username: ${{ secrets.DIGITALOCEANUSERNAME }}
          password: ${{ secrets.DIGITALOCEANPASSWORD }}
          script: |
           echo "Image tag: ${{ steps.build-image.outputs.image-tag }}"
           docker run --name activofijo -d -p 80:80 my-image-name:latest
