name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      # Crea el archivo appsettings.json
    - name: Set up appconfig.development.json
      run: |
          # Crear appconfig.json
          echo '{
          "env": "Development"
          //"env": "Local",
          //"env": "Production",
          //"env": "Qa"
          }'  > appconfig.json
          echo '{
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetcore": "Warning"
              }
            },
            "env": "Development",
            "AllowedHosts": "*",
            "ConnectionStrings": {
              "Netcore": "'"$NETCORE"'"
            },
            "Secret": "'"$SECRETKEY"'",
          }' > appsettings.temp.json
          mv appsettings.temp.json appsettings.Development.json

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Setup SSH
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
        - name: Deploy to DigitalOcean
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DIGITALOCEAN_HOST }}
            username: ${{ secrets.DIGITALOCEAN_USERNAME }}
            password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
            script: |
              docker stop activofijo || true
              docker rm activofijo || true
              docker run --name activofijo -d -p 9000:80 my-image-name:$(date +%s)
