name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        id: build-image
        run: |
          docker build . --file Dockerfile --tag my-image-name:latest
          docker push my-image-name:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEANHOST }}
          username: ${{ secrets.DIGITALOCEANUSERNAME }}
          password: ${{ secrets.DIGITALOCEANPASSWORD }}
          script: |
            docker stop activofijo || true
            docker rm activofijo || true
            docker pull my-image-name:latest
            docker run --name activofijo -d -p 80:80 my-image-name:latest
