name: Docker Image CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build . -f Dockerfile -t my-image-name:latest
          docker save my-image-name:latest > my-image.tar

      - name: Copy Docker image to DigitalOcean droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          port: 22
          source: my-image.tar
          target: /tmp/my-image.tar

      - name: Load Docker image on DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          port: 22
          script: |
            docker load < /tmp/my-image.tar
            docker run --name activofijo -d -p 80:80 my-image-name:latest
