name: CI

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: vinayb21/github-action-push-to-another-repo@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'Castellano-SVN'
          destination-repository-name: 'NetcoreActivoFijo'
          user-email: cesar.laraperalta@gmail.com
          commit-message: UPDATE BOT
