name: deploy-me
'on':
    - push
jobs:
    deploy-me:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            - run: |
                  ls
                  git config --global user.email "cesar.laraperalta@gmail.com"
                  git config --global user.name "Cesar lara@automationGITHUB-ACTION"
                  git config --global credential.helper cache
                  git clone https://${{secrets.GITHUB_TOKEN}}@github.com/Castellano-SVN/NetcoreActivoFijo
                  cp . NetcoreActivoFijo/ -f
                  cd NetcoreActivoFijo
                  rm .github
                  git add .
                  git commit -m "$(date)"
                  git push
